"""N06 — Jobs / Redis / Celery. Generated by Konnaxion Mega Diagnostic Pack."""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from levelupdiag_core.config import AppConfig, load_config
from konnaxion_diag.checks import run_domain

LEVEL_ID = "N06"
LEVEL_NAME = "Jobs / Redis / Celery"
PURPOSE = "Validate background-task tests and optional live job probes."

def run(config: AppConfig | None = None):
    cfg = load_config() if config is None else config
    return run_domain(cfg, LEVEL_ID, LEVEL_NAME)

if __name__ == "__main__":
    from levelupdiag_core.verdicts import exit_code
    raise SystemExit(exit_code(run().verdict))
